config/routes.rb
#                 new_sense GET    /senses/new(.:format)                                                                    senses#new
#                edit_sense GET    /senses/:id/edit(.:format)                                                               senses#edit
#                     sense GET    /senses/:id(.:format)                                                                    senses#show
#                           PATCH  /senses/:id(.:format)                                                                    senses#update
#                           PUT    /senses/:id(.:format)                                                                    senses#update
#                           DELETE /senses/:id(.:format)                                                                    senses#destroy
#                      tags GET    /tags(.:format)                                                                          tags#index
#                           POST   /tags(.:format)                                                                          tags#create
#                   new_tag GET    /tags/new(.:format)                                                                      tags#new
#                  edit_tag GET    /tags/:id/edit(.:format)                                                                 tags#edit
#                       tag GET    /tags/:id(.:format)                                                                      tags#show
#                           PATCH  /tags/:id(.:format)                                                                      tags#update
#                           PUT    /tags/:id(.:format)                                                                      tags#update
#                           DELETE /tags/:id(.:format)                                                                      tags#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PUT    /users(.:format)                                                                         devise/registrations#update
#        delete_image_diary PUT    /diaries/:id/delete_image(.:format)                                                      diaries#delete_image
#              cancel_diary GET    /diaries/:id/cancel(.:format)                                                            diaries#cancel
#           hilight_diaries GET    /diaries/hilight(.:format)                                                               diaries#hilight
#             years_diaries GET    /diaries/years/:year(.:format)                                                           diaries#years
#       append_memo_diaries POST   /diaries/append_memo(.:format)                                                           diaries#append_memo
#                   diaries GET    /diaries(.:format)                                                                       diaries#index
#                           POST   /diaries(.:format)                                                                       diaries#create
#                 new_diary GET    /diaries/new(.:format)                                                                   diaries#new
#                edit_diary GET    /diaries/:id/edit(.:format)                                                              diaries#edit
#                     diary GET    /diaries/:id(.:format)                                                                   diaries#show
#                           PATCH  /diaries/:id(.:format)                                                                   diaries#update
#                           PUT    /diaries/:id(.:format)                                                                   diaries#update
#                           DELETE /diaries/:id(.:format)                                                                   diaries#destroy
#             result_habits GET    /habits/result(.:format)                                                                 habits#result
#                top_habits GET    /habits/top(.:format)                                                                    habits#top
#                    habits GET    /habits(.:format)                                                                        habits#index
#                           POST   /habits(.:format)                                                                        habits#create
#                 new_habit GET    /habits/new(.:format)                                                                    habits#new
#                edit_habit GET    /habits/:id/edit(.:format)                                                               habits#edit
#                     habit GET    /habits/:id(.:format)                                                                    habits#show
#                           PATCH  /habits/:id(.:format)                                                                    habits#update
#                           PUT    /habits/:id(.:format)                                                                    habits#update
#                           DELETE /habits/:id(.:format)                                                                    habits#destroy
#  update_or_create_records POST   /records/update_or_create(.:format)                                                      records#update_or_create
#                           PUT    /records/update_or_create(.:format)                                                      records#update_or_create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  ### for API
  namespace 'api' do
    namespace 'v1' do
      post 'sign_in' => 'sessions#create'
      get 'diaries/latest' => 'diaries#latest'
      post 'diaries/:id' => 'diaries#append_memo'
      post 'diaries' => 'diaries#create'
      get 'diaries/:id' => 'diaries#show'
    end
  end

  ### for web
  root to: 'general#day'
  get 'day/:date', to: 'general#day', as: :day
  get 'day_data/:date', to: 'general#day_data'
  get 'month', to: 'general#month', as: :this_month
  get 'month/:month', to: 'general#month', as: :month
  # 日記のURLに日付が含まれていれば、URLの情報として便利かと思ったが、なくても良かったかも
  get '/day/:date/diaries/:id', to: 'diaries#show', as: 'diary_with_date', constraints: { date: /\d{4}-\d{1,2}-\d{1,2}/ }

  scope :search do
    get '' => 'search#top', as: :search
    get ':content_type' => 'search#content'
  end

  resources :habitodos, except: [:new, :show, :edit] do
    collection do
      get 'get_data'
    end
  end

  resources :senses do
    collection do
      get 'past'
      get 'current'
    end
  end

  resources :tags

  # mount RailsAdmin::Engine => '/adamin', :as => 'rails_admin'

  # devise_for :admins

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :todos do
    collection do
      put :bulk_update
    end
  end
  resources :todo_projects, except: %i[show]
  get 'gcp-oauth-callback', to: 'todos#google_callback', as: :google_callback

  resources :diaries do
    member do
      put :delete_image
      put 'delete_sub_image/:image_id', action: :delete_sub_image
      post :create_image
      post :update_categories
      get :histories
    end
    collection do
      get 'hilight'
      get 'years/:year', action: :years, as: :years
      post 'append_memo'
      get 'pinned'
    end
  end

  resources :categories do
    collection do
      get :manage
      get :selection
    end
  end

  resources :habits
  resources :records, only: [:create, :update]

  resources :children, except: %i[index show] do
    member do
      get :graph
    end

app/models/diary/html_converter.rb
require 'open-uri'

# contentEditableにコピペされたhtmlから余計なものを削除したり、画像を持ってきてHMの画像にして、content内容を置換するクラス
class Diary::HtmlConverter
  attr_reader :converted_content, :uploaded_images

  # @param [String] contentEditableの内容
  def initialize(content)
    @converted_content = content
    @uploaded_images = []
  end

  def convert
    remove_tw_attributes
    remove_source_tags
    image_urls = extract_image_urls
    replace_with_active_storage_urls(image_urls)
  end

  private

  # cookpadレシピのhtml style内に含まれる「--tw-xxx」という属性を削除（大量にあるので、文字数削減のため）
  # styleごと削除しちゃうとレイアウトが崩れるのでうまいこと削除する
  # ex. style="--tw-border-spacing-x: 0; margin-top: calc(1rem*(1 - var(--tw-space-y-reverse)));" みたいな文字列
  def remove_tw_attributes
    @converted_content.gsub!(/--tw-[\w-]+:[^;]*;|--tw-[\w-]+\b/, '')
  end

  def remove_source_tags
    # NOTE: \bは単語境界。<sourcefoo>などのタグを誤って検知しないように
    # NOTE: .*?の最短マッチより、[^>]*のほうが使いやすそう（どっかで、後者じゃないと成功しないケースがあったが見失った）
    @converted_content.gsub!(/<source\b[^>]*>/, '')
  end

  # content中の <img> タグの src 属性から画像URLを抽出
  def extract_image_urls
    # 正規表現で <img> タグの src 属性を抽出
    @converted_content.scan(/<img[^>]+src=["']([^"']+)["']/i).flatten
  end

  # 画像URLからダウンロードし、ActiveStorageに保存して、そのURLで置換する
  def replace_with_active_storage_urls(image_urls)
    image_urls.each do |image_url|
      next if already_saved?(image_url)

      begin
        # 画像をダウンロード
        decoded_image_url = CGI.unescapeHTML(image_url) # &が&amp;のようにエスケープされているのをデコードする
        downloaded_image = URI.open(decoded_image_url)
        filename = URI.decode_www_form_component(File.basename(URI.parse(image_url).path))

        # attachだとモデルのsave後に処理されてしまい、attachの時点では正確な画像URLが取得できないので、即時処理されるcreate_and_upload!を使う
        blob = ActiveStorage::Blob.create_and_upload!(
          io: downloaded_image,
          filename:,
          content_type: downloaded_image.content_type
        )

        # ActiveStorageのURLに置換
        # 貼り付けたhtml内の画像はサムネイル画像サイズ想定のため、ActiveStorageではリサイズせずオリジナルを使う
        @converted_content.gsub!(image_url, Rails.application.routes.url_helpers.url_for(blob))

        @uploaded_images << blob
      end
    end
  end

  def already_saved?(image_url)
    image_url.start_with?(Rails.application.routes.url_helpers.root_url)
  end
end

app/controllers/api/v1/diaries_controller.rb
module Api
  module V1
    class DiariesController < ApiController
      before_action :authenticate_user_for_api
      before_action :set_diary, only: [:show, :append_memo]

      # 「やったこと」など特定のタグがついた日記を本日より指定日数前からの分を取得する
      def latest
        tag = params[:tag]
        latest_term = build_term(params[:limit])
        diaries = current_user.diaries.tagged_with(tag).where(record_at: latest_term).order("record_at DESC")

        # 期間の範囲分のDiaryを返したいので、DBに存在しない場合はインスタンス作って埋める
        result = []
        latest_term.each do |date|
          found_in_db = diaries.select { |d| d.record_at == date }
          if found_in_db.present?
            result += found_in_db
          else
            result << Diary.new(record_at: date)
          end
        end
        # todo: jsonBuilderで情報を絞りたいところ
        render json: result.reverse
      end

      def append_memo
        @diary.append_memo(params[:memo])
        @diary.save
        render json: @diary, status: :ok
      end

      def create
        p params
        diary = current_user.diaries.build(record_at: params[:record_at])
        diary.tag_list << params[:tag]
        diary.append_memo(params[:memo])
        diary.save
        render json: diary, status: :ok
      end

      # todo: 使わないかな
      def show
        render json: @diary
      end


      private

      def set_diary
        @diary = Diary.find(params[:id])
      end

      def build_term(limit)
        lim = limit.blank? ? 5 : limit.to_i
        start_date = Date.today - (lim - 1)
        start_date..Date.today
      end
    end
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
  def tags_link(diary)
    output = ""
    diary.tags.each do |tag|
      custom_tag = CustomTag.new(tag.attributes)
      output += link_to tag.name, diaries_path(tag: tag.name), class: "badge mr5", style: custom_tag.color_style
    end
    return output.html_safe
  end

  # monthページで表示する日記コンテンツ
  def show_diary_for_month(diary)
    output = ""
    tags = tags_link(diary)

    output += "<span class='mr5 badge badge-danger'>ｼｰｸﾚｯﾄ</span>".html_safe if diary.is_secret
    output += "<span class='badge badge-warning'>ﾊｲﾗｲﾄ</span>".html_safe if diary.is_hilight
    output += "<br>".html_safe if diary.is_hilight or diary.is_secret
    output += tags + "<br>".html_safe if tags.present?
    output += "<i class='fa fa-star text-danger'></i>" if diary.main_in_day.present?
    output += "<strong>" + (link_to diary.title_mod, diary_with_date_path(diary.record_at, diary), class: 'diary-title') + "</strong>"
    # ここから日記編集は不要かなー（編集画面をなくしたのでUIを作るのもメンドイし）
    # output += " " + (link_to fa_icon('pencil'), edit_diary_path(diary)) + "<br>"
    output += image_tag(diary.eyecatch_image_small, class: "img-thumbnail") + "<br>".html_safe if diary.eyecatch_image.attached?
    return output.html_safe
  end

  # dayページの日記一覧リンクの表示のために使用
  # NOTE: content_tagではなくtagを使うこと
  def diary_links_list(diaries)
    tag.ul do |tag|
      diaries.each do |diary|
        title = diary.title.presence || '（タイトルなし）'
        concat tag.li(link_to(title, diary_with_date_path(diary.record_at, diary)) + " " + tags_link(diary))
      end
    end
  end
end

app/views/diaries/_index_detail.html.slim
.well
  .page-header.mt0
    .d-flex.justify-content-end
      .flex-grow-1
        h5.diary-title
          - unless is_day_page
            span.date.mr10 = link_to fa_icon('calendar', text: dispdate(diary.record_at, true)), day_path(diary.record_at)
          span.title = link_to diary.title_mod, diary_with_date_path(diary.record_at, diary)
      .tags.ml-3 = tags_link(diary)
  = "<p class='btn btn-block btn-danger disabled mb5'>シークレット日記</p>".html_safe if diary.is_secret
  = "<p class='btn btn-block btn-warning disabled mb5'>ハイライト日記</p>".html_safe if diary.is_hilight
  .text-center.mt20
    = image_tag(diary.eyecatch_image_small, class: "w-50 img-thumbnail") if diary.eyecatch_image.attached?
  .markdown
    = markdown(diary.content)
  - if is_day_page
    .buttons
      = link_to '編集', edit_diary_path(diary), class: "btn btn-light ignore-checking-changes", remote: true

app/views/diaries/everyday.html.slim
.mb-3
  - if @all.present?
    = link_to '短縮表示', everyday_diaries_path, class: 'btn btn-info'
  - else
    = link_to '全文表示', everyday_diaries_path(all: '1'), class: 'btn btn-info'

ul.mb-4
  li = link_to 'すべてのタグ', everyday_diaries_path(all: '1')
  - @tag_names.each do |tag_name|
    li = link_to tag_name, everyday_diaries_path(all: '1', tag: tag_name)

- @diaries.each do |diary|
  .card.mb-3
    h5.card-header.p-2
      .d-flex.justify-content-end
        .flex-grow-1
          span.date.mr10 = link_to fa_icon('calendar', text: dispdate(diary.record_at, true)), day_path(diary.record_at)
          span.title = link_to diary.title_mod, diary_path(diary)
        small.tags.ml-3 = tags_link(diary)
    .card-body.p-2
      = image_tag(diary.image(:small), class: "w-50 img-thumbnail") if diary.image.present?
      - if @all.present?
        = markdown(diary.content)
      - else
        = diary.content.truncate(150)

app/views/diaries/hilight.html.slim
.row.justify-content-center.mt15
  .col-sm-2
    .years
      - @years_including_diaries_count.each do |year, count|
        - disable_class = year.to_i == @year.to_i ? "disabled" : ""
        p.mb10 = link_to "#{year}年<span class='badge badge-light ml5'>#{count}</span>".html_safe,
                         hilight_diaries_path(year: year), class: "btn btn-primary btn-block #{disable_class}"
  .col-sm-6.order-2.order-sm-1
    .mt10
      = link_to "隠しも表示", hilight_diaries_path(nosecret: true, year: @year), class: "btn btn-light"
    - @diaries.each do |diary|
      .page-header
        .d-flex.justify-content-end
          .flex-grow-1
            h5.diary-title id="diary#{diary.id}"
              span.date = link_to fa_icon('calendar', text: dispdate(diary.record_at, true)), day_path(diary.record_at)
              = " ほど" if diary.is_about_date.present?
              span.title.ml10 = link_to diary.title_mod, diary_with_date_path(diary.record_at, diary)
          .tags.ml-3 = tags_link(diary)
      .well.well2
        p.mb25
          = link_to(image_tag(diary.eyecatch_image_large, width: "100%", class: "img-thumbnail"), diary.eyecatch_image) if diary.eyecatch_image.attached?
        .markdown
          = markdown(diary.content)
  .col-sm-3.order-1.order-sm-2
    .card
      ul.list-group.list-group-flush
        - @diaries.each do |diary|
          li.list-group-item
            = link_to "#{dispdate(diary.record_at, false)} #{diary.title_mod}", "#diary#{diary.id}"

app/views/diaries/histories.html.slim
.row.justify-content-center
  .col-sm-10
    = link_to '日記ページに戻る', diary_with_date_path(@diary.record_at, @diary), class: 'btn btn-light'
    .page-header
      h2 変更履歴
    table.table.table-bordered
      thead
        tr
          th(style="min-width:120px")
          th 現在
          th 過去
      tbody
        tr
          td 変更者
          td = @history.user.dispname
        - @history.changed_prev_attrs.each do |key, val|
          tr
            td = key
            td
              - if @diary[key].is_a?(String)
                = simple_format @diary[key]
              - else
                = @diary[key]
            td
              - if val.is_a?(String)
                = simple_format val
              - else
                = val

app/views/diaries/index.html.slim
.row.justify-content-center
  / スマホではタグのボックスが最初になるようにする
  .col-sm-6.order-2.order-sm-1
    .page-header
      h3
        | 日記一覧
        small.badge.badge-pill.badge-warning.ml20 =< "取得数：#{@diaries.total_count}"
    .search-form.mb30
      = simple_form_for(@q, method: "get") do |f|
        = f.input :search_word, as: :string, label: false, placeholder: "例：あああ　いいい　tags:AAA,BBB　hilight:1　image:1 since:年月日　until:年月日　year:年"
        = f.submit "検索する", class: "btn btn-info"
        =< link_to "検索解除", diaries_path, class: "btn btn-light" if @q.search_word.present?
    = paginate @diaries, window: 3, outer_window: 2
    - @diaries.each do |diary|
      = render partial: 'index_detail', locals: { diary: diary, is_day_page: false }
    .mt30
      = paginate @diaries, window: 3, outer_window: 2

  .col-sm-2.order-1.order-sm-2
    .card.mt15
      .accordion#accordionExample
        .card-header data-toggle="collapse" data-target="#collapseOne" style="cursor: pointer;"
          h4
            button.btn.btn-link style="padding:0;font-size:1em;" タグ
        #collapseOne class="collapse #{browser.device.mobile? ? '' : 'show'}" data-parent="#accordionExample"
          ul.list-group.list-group-flush
            - @tags.each do |tag|
              li.list-group-item
                = fa_icon('thumb-tack') + "&nbsp;".html_safe if tag.pinned?
                = link_to "#{tag.name} (#{tag.taggings_count})", diaries_path(tag: tag.name)
          .card-footer
            = link_to "タグ管理", tags_path, class: "card-link"

app/views/diaries/pinned.html.slim
.mb-3
  - if @all.present?
    = link_to '短縮表示', pinned_diaries_path, class: 'btn btn-info'
  - else
    = link_to '全文表示', pinned_diaries_path(all: '1'), class: 'btn btn-info'

ul.mb-4
  li = link_to 'すべてのタグ', pinned_diaries_path(all: '1')
  - @tag_names.each do |tag_name|
    li = link_to tag_name, pinned_diaries_path(all: '1', tag: tag_name)

- @diaries.each do |diary|
  .card.mb-3
    h5.card-header.p-2
      .d-flex.justify-content-end
        .flex-grow-1
          span.date.mr10 = link_to fa_icon('calendar', text: dispdate(diary.record_at, true)), day_path(diary.record_at)
          span.title = link_to diary.title_mod, diary_with_date_path(diary.record_at, diary)
        small.tags.ml-3 = tags_link(diary)
    .card-body.p-2
      = image_tag(diary.eyecatch_image_small, class: "w-50 img-thumbnail") if diary.eyecatch_image.attached?
      - if @all.present?
        .markdown = markdown(diary.content)
      - else
        = diary.content.truncate(150)

app/views/diaries/show.html.slim
- content_for :addjs_in_head
  = javascript_pack_tag 'diary_show', 'data-turbolinks-track': 'reload'

#diaryShow
  .row.justify-content-center
    .col-sm-7
      .d-flex.justify-content-end
        .mb-4
          url-copy-button
      diary(
        :diary-id="#{@diary.id}"
        :modal-mode="true"
        :target-date-for-edit-mode="null"
        :categories="categories"
      )

      / 日記の検索フォームに初期値ありで検索できるリンクは良い感じなので、コメントアウトして残しておこう
      / =< link_to "#{@diary.record_at.year}年の日記", diaries_path("diary[search_word]" => "year:#{@diary.record_at.year}"), class: "btn btn-light"

app/views/diaries/years.html.slim
.d-flex.justify-content-between.mt10.mb15
  = link_to fa_icon('caret-left', class: 'fa-lg', style: 'padding:0.6em 0.1em'), years_diaries_path(@year -1), class: "btn btn-light"
  .text-center
    span.text-140.mr-2 = "#{@year}年"
    = link_to '年選択', '#', class: 'btn btn-light dropdown-toggle', data: {toggle: 'dropdown'}
    .dropdown-menu
      - Date.today.year.step(Settings.start_year, -1).each do |year|
        = link_to year, years_diaries_path(year), class: 'dropdown-item'
  = link_to fa_icon('caret-right', class: 'fa-lg', style: 'padding:0.6em 0.1em'), years_diaries_path(@year + 1), class: "btn btn-light"

table.table.table-bordered.ten-years-diaries
  thead
    tr
      th.day
      - (1..12).each do |month|
        th = "#{month}月"
  tbody
    - (1..31).each do |day|
      tr
        td.day = day
        - (1..12).each do |month|
          - date = Date.parse("#{@year}/#{month}/#{day}") rescue nil
          - if date.present?
            td
              = link_to day_path("#{@year}-#{month}-#{day}") do
                .badge.badge-light.w100.p-1 = "#{month}/#{day} (#{@diaries_by_date[month][day].size})"
              - @diaries_by_date[month][day].each do |diary|
                .text-underline = fa_icon 'square', text: diary.title if diary.title.present?
          - else
            td.bg-secondary