config/routes.rb
#                           DELETE /senses/:id(.:format)                                                                    senses#destroy
#                      tags GET    /tags(.:format)                                                                          tags#index
#                           POST   /tags(.:format)                                                                          tags#create
#                   new_tag GET    /tags/new(.:format)                                                                      tags#new
#                  edit_tag GET    /tags/:id/edit(.:format)                                                                 tags#edit
#                       tag GET    /tags/:id(.:format)                                                                      tags#show
#                           PATCH  /tags/:id(.:format)                                                                      tags#update
#                           PUT    /tags/:id(.:format)                                                                      tags#update
#                           DELETE /tags/:id(.:format)                                                                      tags#destroy
#          new_user_session GET    /users/sign_in(.:format)                                                                 devise/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 devise/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                devise/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            devise/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           devise/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                devise/passwords#update
#                           PUT    /users/password(.:format)                                                                devise/passwords#update
#                           POST   /users/password(.:format)                                                                devise/passwords#create
#    edit_user_registration GET    /users/edit(.:format)                                                                    devise/registrations#edit
#         user_registration PUT    /users(.:format)                                                                         devise/registrations#update
#        delete_image_diary PUT    /diaries/:id/delete_image(.:format)                                                      diaries#delete_image
#              cancel_diary GET    /diaries/:id/cancel(.:format)                                                            diaries#cancel
#           hilight_diaries GET    /diaries/hilight(.:format)                                                               diaries#hilight
#             years_diaries GET    /diaries/years/:year(.:format)                                                           diaries#years
#       append_memo_diaries POST   /diaries/append_memo(.:format)                                                           diaries#append_memo
#                   diaries GET    /diaries(.:format)                                                                       diaries#index
#                           POST   /diaries(.:format)                                                                       diaries#create
#                 new_diary GET    /diaries/new(.:format)                                                                   diaries#new
#                edit_diary GET    /diaries/:id/edit(.:format)                                                              diaries#edit
#                     diary GET    /diaries/:id(.:format)                                                                   diaries#show
#                           PATCH  /diaries/:id(.:format)                                                                   diaries#update
#                           PUT    /diaries/:id(.:format)                                                                   diaries#update
#                           DELETE /diaries/:id(.:format)                                                                   diaries#destroy
#             result_habits GET    /habits/result(.:format)                                                                 habits#result
#                top_habits GET    /habits/top(.:format)                                                                    habits#top
#                    habits GET    /habits(.:format)                                                                        habits#index
#                           POST   /habits(.:format)                                                                        habits#create
#                 new_habit GET    /habits/new(.:format)                                                                    habits#new
#                edit_habit GET    /habits/:id/edit(.:format)                                                               habits#edit
#                     habit GET    /habits/:id(.:format)                                                                    habits#show
#                           PATCH  /habits/:id(.:format)                                                                    habits#update
#                           PUT    /habits/:id(.:format)                                                                    habits#update
#                           DELETE /habits/:id(.:format)                                                                    habits#destroy
#  update_or_create_records POST   /records/update_or_create(.:format)                                                      records#update_or_create
#                           PUT    /records/update_or_create(.:format)                                                      records#update_or_create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  ### for API
  namespace 'api' do
    namespace 'v1' do
      post 'sign_in' => 'sessions#create'
      get 'diaries/latest' => 'diaries#latest'
      post 'diaries/:id' => 'diaries#append_memo'
      post 'diaries' => 'diaries#create'
      get 'diaries/:id' => 'diaries#show'
    end
  end

  ### for web
  root to: 'general#day'
  get 'day/:date', to: 'general#day', as: :day
  get 'day_data/:date', to: 'general#day_data'
  get 'month', to: 'general#month', as: :this_month
  get 'month/:month', to: 'general#month', as: :month
  # 日記のURLに日付が含まれていれば、URLの情報として便利かと思ったが、なくても良かったかも
  get '/day/:date/diaries/:id', to: 'diaries#show', as: 'diary_with_date', constraints: { date: /\d{4}-\d{1,2}-\d{1,2}/ }

  scope :search do
    get '' => 'search#top', as: :search
    get ':content_type' => 'search#content'
  end

  resources :habitodos, except: [:new, :show, :edit] do
    collection do
      get 'get_data'
    end
  end

  resources :senses do
    collection do
      get 'past'
      get 'current'
    end
  end

  resources :tags

  # mount RailsAdmin::Engine => '/adamin', :as => 'rails_admin'

  # devise_for :admins

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :todos do
    collection do
      put :bulk_update
    end
  end
  resources :todo_projects, except: %i[show]
  get 'gcp-oauth-callback', to: 'todos#google_callback', as: :google_callback

  resources :diaries do
    member do
      put :delete_image
      put 'delete_sub_image/:image_id', action: :delete_sub_image
      post :create_image
      post :update_categories
      get :histories
    end
    collection do
      get 'hilight'
      get 'years/:year', action: :years, as: :years
      post 'append_memo'
      get 'pinned'
    end
  end

  resources :categories do
    collection do
      get :manage
      get :selection
    end
  end

  resources :habits
  resources :records, only: [:create, :update]

  resources :children, except: %i[index show] do
    member do
      get :graph
    end

    resources :child_histories, path: :histories, only: [:create, :edit, :update, :destroy] do
      collection do
        get 'y/:year', action: :year, as: :year
        get 'm/:year/:month', action: :month, as: :month
      end
    end
  end

  resource :family, only: %i[show edit update] do
    member do
      get :all_histories
    end
    resources :family_histories, path: :histories, only: [:index, :create, :edit, :update, :destroy] do
      collection do
        get 'y/:year', action: :year, as: :year
        get 'm/:year/:month', action: :month, as: :month
      end
    end
  end

  # devise + α
  resources :users, only: [] do
    resources :user_histories, path: :histories, only: [:index, :create, :edit, :update, :destroy] do
      collection do

app/models/family.rb
# == Schema Information
#
# Table name: families
#
#  id         :bigint           not null, primary key
#  enabled    :boolean          default(FALSE), not null
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Family < ApplicationRecord
  # TODO: enabled は、「家族」メニューを非表示にしたい時が出てきた時に利用する
  has_many :users
  has_many :children
  has_many :histories, as: :source
  has_many :all_histories, class_name: 'History'
  has_many :habits, as: :source

  def name_with_suffix
    "#{name}家"
  end

  def dispname
    name_with_suffix
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :authenticate_user!

  def show
    @users = current_family.users
    @children = current_family.children
    @histories_count_hash = build_histories_count_hash(current_family)
    @content_title = '家族ページ'
  end

  def edit
  end

  def update
    current_family.update(family_params)
    redirect_to family_path, notice: '更新しました'
  end

  # Family#historiesのことではなく、Family内のすべてのユーザーのHistory
  def all_histories
    @histories = current_family.all_histories.includes(:source).newer.page(params[:page]).per(50)
  end

  private

  def family_params
    params.require(:family).permit(:name)
  end

  def build_histories_count_hash(family)
    {
      children: family.children.includes(:histories).map { [_1.id, _1.histories.count] }.to_h,
      users: family.users.includes(:histories).map { [_1.id, _1.histories.count] }.to_h,
      family: family.histories.count
    }
  end
end

app/views/families/_form.html.slim
= form_with(model: current_family, class: 'form') do |f|
  - if current_family.errors.any?
    .alert.alert-danger
      ul
        - current_family.errors.full_messages.each do |msg|
          li = msg

  .form-group
    = f.label :name, "表示名"
    = f.text_field :name, class: 'form-control'

  = f.submit '登録する', class: "btn btn-primary"

app/views/families/_header.html.slim
.row.pt-1.pb-1
  - home_path = month_family_family_histories_path(Time.now.year, Time.now.month)
  - if defined?(family.profile_image) && family.profile_image.present?
    = link_to image_tag(family.profile_image.url(:small), class: 'rounded-circle', width: '65px', height: '65px'), home_path
  .flex-grow-1.align-self-center
    h3.ml-2
      = link_to family.name_with_suffix, home_path, class: 'text-light'
  .align-self-center
    = yield :family_header_actions

app/views/families/all_histories.html.slim
.row.justify-content-center
  .col-sm(style="max-width: 500px")
    = link_to '家族ページへ', family_path, class: 'btn btn-light'
    .page-header
      h2 みんなの記録一覧
    - if @histories.blank?
      p
        | 記録はありません。
    - else
      = paginate @histories, window: 3, outer_window: 2
      - @histories.each do |history|
        .card.mb-3(id="history-#{history.target_date.to_s}")
          .card-header
            .row.justify-content-between
              .col-7
                - if history.about_date
                  span.mr-1.text-muted = "(だいたい)"
                = dispdate(history.target_date, true)
                span.badge.badge-pill.badge-warning.ml-3.p-1 = "#{history.source.dispname}の記録"
              .col-5.m-auto.text-right
                = link_to fa_icon('external-link', text: "#{history.source.dispname}のページ"), each_user_history_path(history), target: '_blank'
          .card-body
            h5.card-title = history.title
            - if history.content.present?
              .card-text.text-muted.markdown = markdown(history.content)
          - if history.data.present?
            ul.list-group.list-group-flush
              - history.data.each do |key, value|
                li.list-group-item.text-muted = "#{History.human_attribute_name("data.#{key}")}: #{value}"
          = link_to image_tag(history.eyecatch_image_small, class: 'card-img-bottom'), history.eyecatch_image_large if history.eyecatch_image.attached?
      = paginate @histories, window: 3, outer_window: 2

app/views/families/edit.html.slim
.row.justify-content-center
  .col-sm-2
    .mb-3 = link_to '戻る', family_path, class: 'btn btn-light'
    h2.mb-4 編集
    = render partial: 'form'

app/views/families/show.html.slim
.row.justify-content-center
  .col-sm-2
    .mb-3
      span.text-muted.font-weight-bold.mr-2
        = fa_icon 'child', text: 'こども'
      = link_to '作成', new_child_path
    - @children.each do |child|
      .d-flex.justify-content-between.mb-2
        .d-flex.flex-grow-1
          - if child.profile_image.present?
            = image_tag child.profile_image, class: 'rounded-circle', width: '75px', height: '75px'
          .ml-3
            h4
              = link_to child.name, month_child_child_histories_path(child, Time.now.year, Time.now.month)
              span.badge.badge-secondary.ml-2 = @histories_count_hash[:children][child.id]
            p.text-muted = child.relative_age(Date.today)
        .edit
          = link_to fa_icon('pencil-square-o', class: 'fa-lg'), edit_child_path(child)
      hr.mb-3

    p.text-muted.font-weight-bold
      = fa_icon 'user', text: '他の家族'
    - @users.each do |user|
      .d-flex.justify-content-between.mb-2
        .d-flex.flex-grow-1
          - if user.profile_image.present?
            = image_tag user.profile_image, class: 'rounded-circle', width: '75px', height: '75px'
          .ml-3.mb-3
            h4
              = link_to user.dispname, month_user_user_histories_path(user, Time.now.year, Time.now.month)
              span.badge.badge-secondary.ml-2 = @histories_count_hash[:users][user.id]
      hr.mb-3

    p.text-muted.font-weight-bold
      = fa_icon 'home', text: '家族事'
    .d-flex.justify-content-between.mb-4
      h4
        = link_to current_family.name_with_suffix, month_family_family_histories_path(Time.now.year, Time.now.month)
        span.badge.badge-secondary.ml-2 = @histories_count_hash[:family]
      .edit
        = link_to fa_icon('pencil-square-o', class: 'fa-lg'), edit_family_path
    hr.mb-3
    = link_to 'みんなの記録一覧', all_histories_family_path, class: 'btn btn-light btn-block'